"""Build or verify the committed minimal ONNX Identity model."""

from __future__ import annotations

from pathlib import Path
import sys

from onnx import TensorProto, helper


_MODEL_PATH = Path(__file__).with_name("minimal_identity.onnx")


def _build_model_bytes() -> bytes:
    graph = helper.make_graph(
        [helper.make_node("Identity", ["input"], ["output"])],
        "minimal_identity",
        [helper.make_tensor_value_info("input", TensorProto.FLOAT, [1])],
        [helper.make_tensor_value_info("output", TensorProto.FLOAT, [1])],
    )
    model = helper.make_model(
        graph,
        opset_imports=[helper.make_opsetid("", 13)],
    )
    model.ir_version = 10
    return model.SerializeToString(deterministic=True)


def _check_arguments(arguments: list[str]) -> bool:
    if not arguments:
        return False
    if arguments == ["--check"]:
        return True
    raise SystemExit("usage: build_minimal_identity_model.py [--check]")


def main() -> int:
    """Create the artifact by default, or report byte drift with ``--check``."""
    expected_bytes = _build_model_bytes()
    if _check_arguments(sys.argv[1:]):
        if _MODEL_PATH.is_file() and _MODEL_PATH.read_bytes() == expected_bytes:
            return 0
        print("minimal_identity.onnx differs from generated bytes", file=sys.stderr)
        return 1

    _MODEL_PATH.write_bytes(expected_bytes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
